version: "3.8"
services:

  db:
    image: postgres:13
    container_name: postgres_ddd-go
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - data_ddd-go:/var/lib/postgresql/data

volumes:
  data_ddd-go:
    driver: local
